
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://db.yfaswdlywcmagmrkhxkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmYXN3ZGx5d2NtYWdtcmtoeGt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NzYxNDksImV4cCI6MjA1MDE1MjE0OX0.4_KmUZGfGDTH0vZ9Q8fVUgM3BX1VQIl6K2pVCZVZz5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
